##Portal Konfiguration DEVELOPER VERSION:
portal.version=RBZ am Schützenpark 2.3.7 (11.01.2024)
portal.defaultpassword=Sommer!2021
portal.logenable=true
portal.defaultexitdate=01.01.2030
portal.ipadrequesturl=http://localhost:8082/request?id=
ldap.server=127.0.0.1
#semar
#ldap.port=390
ldap.port=389

ldap.cn=cn=admin,dc=rbz-sp,dc=de
ldap.domain=dc=rbz-sp,dc=de

ldap.password=TEsxOCNnbG9iYWw=
ldap.tls=no
ldap.rootou=ou=schule
ldap.studentsrole=cn=StudentsRole
ldap.teachersrole=cn=TeachersRole
ldap.adminsrole=cn=AdminsRole
ldap.rolesou=ou=Groups
#mailing:
mail.address=noreply@rbz-sp.de
mail.from=noreply@rbz-sp.de
mail.password=Keine!Antwort;2020
mail.smtphost=smtp.strato.de
mail.smtpport=465
mail.smtpauth=true
mail.smtpssl=true
mail.ipadmessage=Für sie ist von ihrer Lehrkraft ein iPad vorgesehen.\nZum Beantragen eines iPads folgen sie bitte folgendem Link:\n 
mail.ipadsubject=Ihr Antrag auf ein Ipad im RBZ am Schützenpark
mail.noipadmessage=Der Antrag, auf ein iPad für Sie, ist von ihrer Lehrkraft zurückgenommen worden.\n Der Link aus der vorherigen Email ist nicht mehr gültig!\n
mail.subject=Ihr RBZ Internetzugang - Email Bestätigung
mail.wellcome=Willkommen im RBZ am Schützenpark.
mail.link=http://localhost:8080/RBZ-Portal/Anmeldung/emailcheck.xhtml?uidNumber=
mail.resetpasswordlink=http://localhost:8080/RBZ-Portal/Password/reset_via_mail.xhtml?userLogin=
#Help:
help.linkteacher=https://nc.rbz-sp.de/index.php/s/7BiH9nxif3tFq4n
help.linkstudents=https://nc.rbz-sp.de/index.php/s/T4wanj9N8gWsZdP
help.linkall=https://nc.rbz-sp.de/index.php/s/9Bckx4HdSgz3nNr
#Links DEVELOP:
oidc.redirecturl=http://localhost:8080/RBZ-Portal
oidc.logouturl=http://localhost:8087/auth/realms/master/protocol/openid-connect/logout
#DATABASE:
mysql.host=jdbc:mariadb://127.0.0.1:3306
mysql.user=portaluser
mysql.password=eCExMzVBYg==
#mysql.password=x!135Ab
#password Klartext = x!135Ab
mysql.database=portal
mysql.tablelog=logging
mysql.tableconfig=config
mysql.tableticket=ticket
