##ini.properties
##Portal LIVE SERVER Konfiguration:
portal.version=RBZ am Schützenpark 3.0.0 (24.01.2024)
portal.defaultpassword=Sommer!2021
portal.logenable=true
portal.defaultexitdate=01.01.2030
portal.ipadrequesturl=https://ia.rbz-sp.de/request?id=
#LDAP:
ldap.server=192.168.200.54
ldap.port=389
ldap.cn=cn=admin,dc=rbz-sp,dc=de
ldap.domain=dc=rbz-sp,dc=de
ldap.password=TEsxOCNnbG9iYWw=
ldap.rootou=ou=schule
ldap.studentsrole=cn=StudentsRole
ldap.teachersrole=cn=TeachersRole
ldap.adminsrole=cn=AdminsRole
ldap.rolesou=ou=Groups
ldap.tls=no
#EMAIL:
mail.address=noreply@rbz-sp.de
mail.from=noreply@rbz-sp.de
mail.password=Keine!Antwort;2020
mail.smtphost=smtp.strato.de
mail.smtpport=465
mail.smtpauth=true
mail.smtpssl=true
mail.ipadmessage=Für sie ist von Ihrer Lehrkraft ein iPad vorgesehen.\nZum Beantragen eines iPads folgen sie bitte folgendem Link:\n 
mail.noipadmessage=Der Antrag, auf ein iPad für Sie, ist zurückgenommen worden.\n Der Link aus der vorherigen Email ist nicht mehr gültig!\n
mail.ipadsubject=Ihr Ipad Antrag im RBZ am Schützenpark
mail.subject=Ihr RBZ Internetzugang - Email Bestätigung
mail.wellcome=Willkommen im RBZ am Schützenpark.
mail.link=https://portal.rbz-sp.de/RBZ-Portal/Anmeldung/emailcheck.xhtml?uidNumber=
mail.resetpasswordlink=https://portal.rbz-sp.de/RBZ-Portal/Password/reset_via_mail.xhtml?userLogin=
#HELP LINK:
help.linkteacher=https://nc.rbz-sp.de/index.php/s/7BiH9nxif3tFq4n
help.linkstudents=https://nc.rbz-sp.de/index.php/s/T4wanj9N8gWsZdP
help.linkall=https://nc.rbz-sp.de/index.php/s/9Bckx4HdSgz3nNr
#KEYCLOAK:
oidc.redirecturl=http://portal.rbz-sp.de/RBZ-Portal
oidc.logouturl=https://kc-sso.rbz-sp.de/auth/realms/master/protocol/openid-connect/logout
#DATABASE
mysql.host=jdbc:mariadb://localhost:3306
mysql.user=portaluser
mysql.password=eCExMzVBYg==
mysql.database=portal
mysql.tablelog=logging
mysql.tableconfig=config
mysql.tableticket=ticket

